 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: shipping-service-deployment
   namespace: abdul-dicoding
   labels:
    app: shipping-service
    type: backend
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: shipping-service
   template:
     metadata:
       labels:
         app: shipping-service
     spec:
       containers:
         - name: shipping-service
           image: ghcr.io/abdulmuhit/shipping-service:latest
           ports:
             - containerPort: 3001
           env:
             - name: PORT
               value: "3001" 
             - name: AMQP_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: proyek-akhir-rabbitmq-secret
                   key: password
             - name: AMQP_USER
               valueFrom:
                 secretKeyRef:
                   name: proyek-akhir-rabbitmq-secret
                   key: user
             - name: AMQP_URL
               value: "amqp://$(AMQP_USER):$(AMQP_PASSWORD)@rabbitmq:5672"
