 apiVersion: v1
 kind: Service
 metadata:
   name: order-service
   namespace: abdul-dicoding
   labels:
     app: order-service
 spec:
   selector:
     app: order-service
   ports:
     - port: 3000
   type: NodePort
