 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: order-service-deployment
   namespace: abdul-dicoding
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: order-service
   template:
     metadata:
       labels:
         app: order-service
         type: backend
     spec:
       containers:
         - name: order-service
           image: ghcr.io/abdulmuhit/order-service:latest
           ports:
             - containerPort: 3000
           env:
             - name: PORT
               value: "3000"
             - name: AMQP_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: proyek-akhir-rabbitmq-secret
                   key: password
             - name: AMQP_USER
               valueFrom:
                 secretKeyRef:
                   name: proyek-akhir-rabbitmq-secret
                   key: user
             - name: AMQP_URL
               value: "amqp://$(AMQP_USER):$(AMQP_PASSWORD)@rabbitmq:5672"
